post:
  summary: Get runtime performance predictions for a GPU-accelerated workload configuration
  security:
    - OAuth2:
      # This operation is accessible by users (openid) and m2m applications with scope gpuradar
      - openid
      - gpuradar
  description: |
    **Get performance predictions for GPU-accelerated training workloads**
    
    This endpoint returns predicted runtime and memory usage (VRAM) for a given training configuration.
    The predictions are provided per GPU type, allowing you to compare performance across different GPU models.
    
    **Request Parameters:**
    - `model_name`: The machine learning model to train
    - `optimizer`: The optimization algorithm (adam or adamw)
    - `batch_size`: Number of samples processed per training step
    - `sequence_length`: Length of input sequences (tokens)
    - `accumulation_steps`: Number of gradient accumulation steps (use 1 for no accumulation)
    
    **Response:**
    - `vram`: Predicted VRAM usage in GB, keyed by GPU type (e.g., "A100", "H100", "RTX4090")
    - `runtime`: Predicted runtime per training step in seconds, keyed by GPU type
  operationId: get-performance-prediction
  tags: [performance-prediction]
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../components/requests/performance-prediction-request.yaml'
        examples:
          llama-training:
            summary: Llama 3.2 3B training configuration
            value:
              model_name: LLAMA3_2_3B
              optimizer: adamw
              batch_size: 4
              sequence_length: 2048
              accumulation_steps: 4
          gemma-training:
            summary: Gemma 3 1B training with gradient accumulation
            value:
              model_name: GEMMA3_1B_IT
              optimizer: adam
              batch_size: 8
              sequence_length: 1024
              accumulation_steps: 2

  responses:
    '200':
      $ref: '../components/responses/performance-prediction-response.yaml'
      useExample: performance-prediction-success
    '400':
      $ref: '../components/responses/error-response.yaml'
      useExample: bad-request
    '422':
      $ref: '../components/responses/error-response.yaml'
      useExample: performance-prediction-unknown-parameter
    '500':
      $ref: '../components/responses/error-response.yaml'
      useExample: server-error