# coding: utf-8

# flake8: noqa

"""
exalsius API

The exalsius REST API enables programmatic access to GPU infrastructure management and orchestration capabilities. Access the API through the `exls` command-line tool or integrate it directly into your applications using standard HTTP requests. The API covers several areas: * **GPU Market Offers** Browse and compare GPU instance pricing across public cloud providers and hyperscalers. * **Operator Integration** Coordinates with the [exalsius-operator](https://github.com/exalsius/exalsius-operator) running in a management Kubernetes cluster to handle infrastructure provisioning and node lifecycle management. * **Node Management** Import cloud-provider instances or self-managed nodes (via SSH) into your node pool. Hardware characteristics of self-managed nodes are discovered automatically. * **Cluster Provisioning** Create and manage Kubernetes clusters on supported cloud providers or self-managed bare-metal infrastructure. * **Service Deployment** Deploy infrastructure services such as the NVIDIA GPU Operator, KubeRay, Flyte, or Kubeflow onto your clusters. * **Workspace Deployment** Provision application workloads including Jupyter Notebook servers, LLM inference services, and other compute workloads on your clusters.

The version of the OpenAPI document: 1.39.0
Contact: support@exalsius.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

__version__ = "1.39.0"

# Define package exports
__all__ = [
    "ClustersApi",
    "ColoniesApi",
    "ManagementApi",
    "NodesApi",
    "OffersApi",
    "PerformancePredictionApi",
    "ServicesApi",
    "VramPredictionApi",
    "WorkspacesApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BaseNode",
    "CloudNode",
    "Cluster",
    "ClusterAddNodeRequest",
    "ClusterAdoptRequest",
    "ClusterCreateRequest",
    "ClusterCreateRequestLocalStorage",
    "ClusterCreateResponse",
    "ClusterDashboardUrlResponse",
    "ClusterDeleteResponse",
    "ClusterDeployResponse",
    "ClusterEventPayload",
    "ClusterEventPayloadInvolvedObject",
    "ClusterKubeconfigResponse",
    "ClusterLocalStorage",
    "ClusterNodeRemoveResponse",
    "ClusterNodeToAdd",
    "ClusterNodesResponse",
    "ClusterResourcesListResponse",
    "ClusterResourcesListResponseResourcesInner",
    "ClusterResponse",
    "ClusterServicesResponse",
    "ClusterTemplate",
    "ClusterTemplateListResponse",
    "ClustersListResponse",
    "ColoniesListResponse",
    "Colony",
    "ColonyCreateRequest",
    "ColonyCreateResponse",
    "ColonyDeleteResponse",
    "ColonyKubeconfigResponse",
    "ColonyResponse",
    "Credentials",
    "CredentialsListResponse",
    "Error",
    "ErrorDetail",
    "GpuTypeInfo",
    "Kubeconfig",
    "NodeDeleteResponse",
    "NodeHardware",
    "NodeImportResponse",
    "NodeImportSshRequest",
    "NodePatchRequest",
    "NodePatchResponse",
    "NodeResponse",
    "NodeSoftware",
    "NodeSystem",
    "NodesListResponse",
    "Offer",
    "OfferMetadataResponse",
    "OffersListResponse",
    "PerformancePrediction",
    "PerformancePredictionRequest",
    "PerformancePredictionResponse",
    "SelfManagedNode",
    "Service",
    "ServiceCreateResponse",
    "ServiceDeleteResponse",
    "ServiceDeployment",
    "ServiceDeploymentCreateRequest",
    "ServiceResponse",
    "ServiceTemplate",
    "ServiceTemplateListResponse",
    "ServicesListResponse",
    "SshKey",
    "SshKeyCreateRequest",
    "SshKeyCreateResponse",
    "SshKeysListResponse",
    "SshKeysListResponseSshKeysInner",
    "VramPredictionMetadataResponse",
    "VramPredictionRequest",
    "VramPredictionResponse",
    "Workspace",
    "WorkspaceAccessInformation",
    "WorkspaceCreateRequest",
    "WorkspaceCreateResponse",
    "WorkspaceDeleteResponse",
    "WorkspaceDeployment",
    "WorkspaceLogPayload",
    "WorkspaceResponse",
    "WorkspaceStartResponse",
    "WorkspaceStopResponse",
    "WorkspaceTemplate",
    "WorkspaceTemplateListResponse",
    "WorkspacesListResponse",
]

# import apis into sdk package
from exalsius_api_client.api.clusters_api import ClustersApi as ClustersApi
from exalsius_api_client.api.colonies_api import ColoniesApi as ColoniesApi
from exalsius_api_client.api.management_api import \
    ManagementApi as ManagementApi
from exalsius_api_client.api.nodes_api import NodesApi as NodesApi
from exalsius_api_client.api.offers_api import OffersApi as OffersApi
from exalsius_api_client.api.performance_prediction_api import \
    PerformancePredictionApi as PerformancePredictionApi
from exalsius_api_client.api.services_api import ServicesApi as ServicesApi
from exalsius_api_client.api.vram_prediction_api import \
    VramPredictionApi as VramPredictionApi
from exalsius_api_client.api.workspaces_api import \
    WorkspacesApi as WorkspacesApi
from exalsius_api_client.api_client import ApiClient as ApiClient
# import ApiClient
from exalsius_api_client.api_response import ApiResponse as ApiResponse
from exalsius_api_client.configuration import Configuration as Configuration
from exalsius_api_client.exceptions import \
    ApiAttributeError as ApiAttributeError
from exalsius_api_client.exceptions import ApiException as ApiException
from exalsius_api_client.exceptions import ApiKeyError as ApiKeyError
from exalsius_api_client.exceptions import ApiTypeError as ApiTypeError
from exalsius_api_client.exceptions import ApiValueError as ApiValueError
from exalsius_api_client.exceptions import OpenApiException as OpenApiException
# import models into sdk package
from exalsius_api_client.models.base_node import BaseNode as BaseNode
from exalsius_api_client.models.cloud_node import CloudNode as CloudNode
from exalsius_api_client.models.cluster import Cluster as Cluster
from exalsius_api_client.models.cluster_add_node_request import \
    ClusterAddNodeRequest as ClusterAddNodeRequest
from exalsius_api_client.models.cluster_adopt_request import \
    ClusterAdoptRequest as ClusterAdoptRequest
from exalsius_api_client.models.cluster_create_request import \
    ClusterCreateRequest as ClusterCreateRequest
from exalsius_api_client.models.cluster_create_request_local_storage import \
    ClusterCreateRequestLocalStorage as ClusterCreateRequestLocalStorage
from exalsius_api_client.models.cluster_create_response import \
    ClusterCreateResponse as ClusterCreateResponse
from exalsius_api_client.models.cluster_dashboard_url_response import \
    ClusterDashboardUrlResponse as ClusterDashboardUrlResponse
from exalsius_api_client.models.cluster_delete_response import \
    ClusterDeleteResponse as ClusterDeleteResponse
from exalsius_api_client.models.cluster_deploy_response import \
    ClusterDeployResponse as ClusterDeployResponse
from exalsius_api_client.models.cluster_event_payload import \
    ClusterEventPayload as ClusterEventPayload
from exalsius_api_client.models.cluster_event_payload_involved_object import \
    ClusterEventPayloadInvolvedObject as ClusterEventPayloadInvolvedObject
from exalsius_api_client.models.cluster_kubeconfig_response import \
    ClusterKubeconfigResponse as ClusterKubeconfigResponse
from exalsius_api_client.models.cluster_local_storage import \
    ClusterLocalStorage as ClusterLocalStorage
from exalsius_api_client.models.cluster_node_remove_response import \
    ClusterNodeRemoveResponse as ClusterNodeRemoveResponse
from exalsius_api_client.models.cluster_node_to_add import \
    ClusterNodeToAdd as ClusterNodeToAdd
from exalsius_api_client.models.cluster_nodes_response import \
    ClusterNodesResponse as ClusterNodesResponse
from exalsius_api_client.models.cluster_resources_list_response import \
    ClusterResourcesListResponse as ClusterResourcesListResponse
from exalsius_api_client.models.cluster_resources_list_response_resources_inner import \
    ClusterResourcesListResponseResourcesInner as \
    ClusterResourcesListResponseResourcesInner
from exalsius_api_client.models.cluster_response import \
    ClusterResponse as ClusterResponse
from exalsius_api_client.models.cluster_services_response import \
    ClusterServicesResponse as ClusterServicesResponse
from exalsius_api_client.models.cluster_template import \
    ClusterTemplate as ClusterTemplate
from exalsius_api_client.models.cluster_template_list_response import \
    ClusterTemplateListResponse as ClusterTemplateListResponse
from exalsius_api_client.models.clusters_list_response import \
    ClustersListResponse as ClustersListResponse
from exalsius_api_client.models.colonies_list_response import \
    ColoniesListResponse as ColoniesListResponse
from exalsius_api_client.models.colony import Colony as Colony
from exalsius_api_client.models.colony_create_request import \
    ColonyCreateRequest as ColonyCreateRequest
from exalsius_api_client.models.colony_create_response import \
    ColonyCreateResponse as ColonyCreateResponse
from exalsius_api_client.models.colony_delete_response import \
    ColonyDeleteResponse as ColonyDeleteResponse
from exalsius_api_client.models.colony_kubeconfig_response import \
    ColonyKubeconfigResponse as ColonyKubeconfigResponse
from exalsius_api_client.models.colony_response import \
    ColonyResponse as ColonyResponse
from exalsius_api_client.models.credentials import Credentials as Credentials
from exalsius_api_client.models.credentials_list_response import \
    CredentialsListResponse as CredentialsListResponse
from exalsius_api_client.models.error import Error as Error
from exalsius_api_client.models.error_detail import ErrorDetail as ErrorDetail
from exalsius_api_client.models.gpu_type_info import GpuTypeInfo as GpuTypeInfo
from exalsius_api_client.models.kubeconfig import Kubeconfig as Kubeconfig
from exalsius_api_client.models.node_delete_response import \
    NodeDeleteResponse as NodeDeleteResponse
from exalsius_api_client.models.node_hardware import \
    NodeHardware as NodeHardware
from exalsius_api_client.models.node_import_response import \
    NodeImportResponse as NodeImportResponse
from exalsius_api_client.models.node_import_ssh_request import \
    NodeImportSshRequest as NodeImportSshRequest
from exalsius_api_client.models.node_patch_request import \
    NodePatchRequest as NodePatchRequest
from exalsius_api_client.models.node_patch_response import \
    NodePatchResponse as NodePatchResponse
from exalsius_api_client.models.node_response import \
    NodeResponse as NodeResponse
from exalsius_api_client.models.node_software import \
    NodeSoftware as NodeSoftware
from exalsius_api_client.models.node_system import NodeSystem as NodeSystem
from exalsius_api_client.models.nodes_list_response import \
    NodesListResponse as NodesListResponse
from exalsius_api_client.models.offer import Offer as Offer
from exalsius_api_client.models.offer_metadata_response import \
    OfferMetadataResponse as OfferMetadataResponse
from exalsius_api_client.models.offers_list_response import \
    OffersListResponse as OffersListResponse
from exalsius_api_client.models.performance_prediction import \
    PerformancePrediction as PerformancePrediction
from exalsius_api_client.models.performance_prediction_request import \
    PerformancePredictionRequest as PerformancePredictionRequest
from exalsius_api_client.models.performance_prediction_response import \
    PerformancePredictionResponse as PerformancePredictionResponse
from exalsius_api_client.models.self_managed_node import \
    SelfManagedNode as SelfManagedNode
from exalsius_api_client.models.service import Service as Service
from exalsius_api_client.models.service_create_response import \
    ServiceCreateResponse as ServiceCreateResponse
from exalsius_api_client.models.service_delete_response import \
    ServiceDeleteResponse as ServiceDeleteResponse
from exalsius_api_client.models.service_deployment import \
    ServiceDeployment as ServiceDeployment
from exalsius_api_client.models.service_deployment_create_request import \
    ServiceDeploymentCreateRequest as ServiceDeploymentCreateRequest
from exalsius_api_client.models.service_response import \
    ServiceResponse as ServiceResponse
from exalsius_api_client.models.service_template import \
    ServiceTemplate as ServiceTemplate
from exalsius_api_client.models.service_template_list_response import \
    ServiceTemplateListResponse as ServiceTemplateListResponse
from exalsius_api_client.models.services_list_response import \
    ServicesListResponse as ServicesListResponse
from exalsius_api_client.models.ssh_key import SshKey as SshKey
from exalsius_api_client.models.ssh_key_create_request import \
    SshKeyCreateRequest as SshKeyCreateRequest
from exalsius_api_client.models.ssh_key_create_response import \
    SshKeyCreateResponse as SshKeyCreateResponse
from exalsius_api_client.models.ssh_keys_list_response import \
    SshKeysListResponse as SshKeysListResponse
from exalsius_api_client.models.ssh_keys_list_response_ssh_keys_inner import \
    SshKeysListResponseSshKeysInner as SshKeysListResponseSshKeysInner
from exalsius_api_client.models.vram_prediction_metadata_response import \
    VramPredictionMetadataResponse as VramPredictionMetadataResponse
from exalsius_api_client.models.vram_prediction_request import \
    VramPredictionRequest as VramPredictionRequest
from exalsius_api_client.models.vram_prediction_response import \
    VramPredictionResponse as VramPredictionResponse
from exalsius_api_client.models.workspace import Workspace as Workspace
from exalsius_api_client.models.workspace_access_information import \
    WorkspaceAccessInformation as WorkspaceAccessInformation
from exalsius_api_client.models.workspace_create_request import \
    WorkspaceCreateRequest as WorkspaceCreateRequest
from exalsius_api_client.models.workspace_create_response import \
    WorkspaceCreateResponse as WorkspaceCreateResponse
from exalsius_api_client.models.workspace_delete_response import \
    WorkspaceDeleteResponse as WorkspaceDeleteResponse
from exalsius_api_client.models.workspace_deployment import \
    WorkspaceDeployment as WorkspaceDeployment
from exalsius_api_client.models.workspace_log_payload import \
    WorkspaceLogPayload as WorkspaceLogPayload
from exalsius_api_client.models.workspace_response import \
    WorkspaceResponse as WorkspaceResponse
from exalsius_api_client.models.workspace_start_response import \
    WorkspaceStartResponse as WorkspaceStartResponse
from exalsius_api_client.models.workspace_stop_response import \
    WorkspaceStopResponse as WorkspaceStopResponse
from exalsius_api_client.models.workspace_template import \
    WorkspaceTemplate as WorkspaceTemplate
from exalsius_api_client.models.workspace_template_list_response import \
    WorkspaceTemplateListResponse as WorkspaceTemplateListResponse
from exalsius_api_client.models.workspaces_list_response import \
    WorkspacesListResponse as WorkspacesListResponse
