# coding: utf-8

"""
exalsius API

The exalsius REST API enables programmatic access to GPU infrastructure management and orchestration capabilities. Access the API through the `exls` command-line tool or integrate it directly into your applications using standard HTTP requests. The API covers several areas: * **GPU Market Offers** Browse and compare GPU instance pricing across public cloud providers and hyperscalers. * **Operator Integration** Coordinates with the [exalsius-operator](https://github.com/exalsius/exalsius-operator) running in a management Kubernetes cluster to handle infrastructure provisioning and node lifecycle management. * **Node Management** Import cloud-provider instances or self-managed nodes (via SSH) into your node pool. Hardware characteristics of self-managed nodes are discovered automatically. * **Cluster Provisioning** Create and manage Kubernetes clusters on supported cloud providers or self-managed bare-metal infrastructure. * **Service Deployment** Deploy infrastructure services such as the NVIDIA GPU Operator, KubeRay, Flyte, or Kubeflow onto your clusters. * **Workspace Deployment** Provision application workloads including Jupyter Notebook servers, LLM inference services, and other compute workloads on your clusters.

The version of the OpenAPI document: 1.32.0
Contact: support@exalsius.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from exalsius_api_client.models.offer_metadata_response import \
    OfferMetadataResponse


class TestOfferMetadataResponse(unittest.TestCase):
    """OfferMetadataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OfferMetadataResponse:
        """Test OfferMetadataResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OfferMetadataResponse`
        """
        model = OfferMetadataResponse()
        if include_optional:
            return OfferMetadataResponse(
                gpu_types = [
                    exalsius_api_client.models.gpu_type_info.gpu-type-info(
                        gpu_type = 'H100', 
                        gpu_vendor = 'NVIDIA', )
                    ],
                gpu_vendors = [
                    'NVIDIA'
                    ],
                cloud_providers = [
                    'AWS'
                    ],
                regions = [
                    ''
                    ],
                availability_zones = [
                    ''
                    ],
                locations = [
                    ''
                    ],
                cpu_vendors = [
                    'INTEL'
                    ],
                cpu_architectures = [
                    'X86_64'
                    ],
                pricing_units = [
                    'HOURLY'
                    ],
                price_types = [
                    'ON_DEMAND'
                    ],
                currencies = [
                    'USD'
                    ],
                gpu_count_min = 56,
                gpu_count_max = 56,
                gpu_memory_mib_min = 56,
                gpu_memory_mib_max = 56,
                total_gpu_memory_mib_min = 56,
                total_gpu_memory_mib_max = 56,
                main_memory_mib_min = 56,
                main_memory_mib_max = 56,
                num_vcpus_min = 56,
                num_vcpus_max = 56,
                price_min = 1.337,
                price_max = 1.337,
                hourly_cost_min = 1.337,
                hourly_cost_max = 1.337
            )
        else:
            return OfferMetadataResponse(
                gpu_types = [
                    exalsius_api_client.models.gpu_type_info.gpu-type-info(
                        gpu_type = 'H100', 
                        gpu_vendor = 'NVIDIA', )
                    ],
                gpu_vendors = [
                    'NVIDIA'
                    ],
                cloud_providers = [
                    'AWS'
                    ],
                regions = [
                    ''
                    ],
                availability_zones = [
                    ''
                    ],
                locations = [
                    ''
                    ],
                cpu_vendors = [
                    'INTEL'
                    ],
                cpu_architectures = [
                    'X86_64'
                    ],
                pricing_units = [
                    'HOURLY'
                    ],
                price_types = [
                    'ON_DEMAND'
                    ],
                currencies = [
                    'USD'
                    ],
                gpu_count_min = 56,
                gpu_count_max = 56,
                gpu_memory_mib_min = 56,
                gpu_memory_mib_max = 56,
                total_gpu_memory_mib_min = 56,
                total_gpu_memory_mib_max = 56,
                main_memory_mib_min = 56,
                main_memory_mib_max = 56,
                num_vcpus_min = 56,
                num_vcpus_max = 56,
                price_min = 1.337,
                price_max = 1.337,
                hourly_cost_min = 1.337,
                hourly_cost_max = 1.337,
        )
        """

    def testOfferMetadataResponse(self):
        """Test OfferMetadataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
