description: The kubeconfig file for a cluster
content:
  application/json:
    schema:
      $ref: '../schemas/cluster-kubeconfig-response.yaml'
    examples:
      success:
        summary: The kubeconfig file for the cluster
        value:
          kubeconfig: |
            apiVersion: v1
            clusters:
              - cluster:
                  server: https://api.exalsius.ai/clusters/123
            users:
              - name: user
                user:
                  token: "123"
            contexts:
              - context:
                  cluster: my-cluster
                  user: user
            current-context: my-cluster