type: object
required:
  - kubeconfig
properties:
  kubeconfig:
    type: string
    description: The kubeconfig for the cluster
    example: |
      apiVersion: v1
      clusters:
        - cluster:
            server: https://api.exalsius.ai/clusters/123e4567-e89b-12d3-a456-426614174000
      users:
        - name: user
          user:
            token: "123"
      contexts:
        - context:
            cluster: my-cluster
            user: user
      current-context: my-cluster
