type: object
properties:
  kubeconfig:
    type: string
    description: The kubeconfig for the cluster
    example: |
      apiVersion: v1
      clusters:
        - cluster:
            server: https://1.2.3.4:6443
          name: exalsius-cluster
      contexts:
        - context:
            cluster: exalsius-cluster
            user: exalsius-user
          name: exalsius-context
      current-context: exalsius-context
      kind: Config
      preferences: {}
