title: NodeAgentDeploymentConfiguration
type: object
required:
  - refresh_token
properties:
  refresh_token:
    type: string
    description: The refresh token for the node agent
    example: "123e4567-e89b-12d3-a456-426614174000"
  