type: object
required:
  - id
  - name
properties:
  id:
    type: integer
    format: int64
    description: The unique identifier for the service
    example: 1
  name:
    type: string
    description: The name of the service
    example: "gpu-operator-24-9-2"
  description:
    type: string
    description: The description of the service
    example: "This is a description of my service"
