type: object
required:
  - id
  - name
properties:
  id:
    type: string
    format: uuid
    description: The unique identifier for the service
    example: "123e4567-e89b-12d3-a456-426614174000"
  name:
    type: string
    description: The name of the service
    example: "gpu-operator-24-9-2"
  description:
    type: string
    description: The description of the service
    example: "This is a description of my service"
