# coding: utf-8

"""
exalsius API

The exalsius REST API enables programmatic access to GPU infrastructure management and orchestration capabilities. Access the API through the `exls` command-line tool or integrate it directly into your applications using standard HTTP requests. The API covers several areas: * **GPU Market Offers** Browse and compare GPU instance pricing across public cloud providers and hyperscalers. * **Operator Integration** Coordinates with the [exalsius-operator](https://github.com/exalsius/exalsius-operator) running in a management Kubernetes cluster to handle infrastructure provisioning and node lifecycle management. * **Node Management** Import cloud-provider instances or self-managed nodes (via SSH) into your node pool. Hardware characteristics of self-managed nodes are discovered automatically. * **Cluster Provisioning** Create and manage Kubernetes clusters on supported cloud providers or self-managed bare-metal infrastructure. * **Service Deployment** Deploy infrastructure services such as the NVIDIA GPU Operator, KubeRay, Flyte, or Kubeflow onto your clusters. * **Workspace Deployment** Provision application workloads including Jupyter Notebook servers, LLM inference services, and other compute workloads on your clusters.

The version of the OpenAPI document: 1.35.0
Contact: support@exalsius.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from importlib import import_module
from typing import (TYPE_CHECKING, Any, ClassVar, Dict, List, Optional, Set,
                    Union)

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator

from exalsius_api_client.models.node_hardware import NodeHardware
from exalsius_api_client.models.node_software import NodeSoftware
from exalsius_api_client.models.node_system import NodeSystem

if TYPE_CHECKING:
    from exalsius_api_client.models.cloud_node import CloudNode
    from exalsius_api_client.models.self_managed_node import SelfManagedNode


class BaseNode(BaseModel):
    """
    BaseNode
    """  # noqa: E501

    id: StrictStr = Field(description="The unique identifier for the node")
    node_type: StrictStr = Field(
        description="The type of the node. - `CLOUD`: Cloud node - `SELF_MANAGED`: Self-managed node "
    )
    namespace: Optional[StrictStr] = Field(
        default=None,
        description="The namespace of the node (e.g. the namespace of the user that added the node)",
    )
    hostname: Optional[StrictStr] = Field(
        default=None, description="The hostname of the node"
    )
    description: Optional[StrictStr] = Field(
        default=None, description="Description of the node"
    )
    location: Optional[StrictStr] = Field(
        default=None,
        description="The location of the node (e.g. city, data center, server rack, etc.)",
    )
    import_time: Optional[datetime] = Field(
        default=None, description="The time the node was imported"
    )
    node_status: StrictStr = Field(
        description="The status of the node. - `PENDING`: Node is pending, e.g. because it wasn't launched yet (CloudNode) or because it wasn't discovered yet (SelfManagedNode) - `DISCOVERING`: Node is being discovered (SSH is checked for SelfManagedNode, Availability for CloudNodes) - `AVAILABLE`: Node is available to be added to a cluster - `ADDED`: Node is added to a cluster - `DEPLOYED`: Node is deployed in a cluster - `FAILED`: The discovering process of the node failed - `WARNING`: Node is in a warning state, e.g., pre-installed software hinders the deployment of the node "
    )
    warning_message: Optional[StrictStr] = Field(
        default=None,
        description="Provides additional information on the warning status, e.g., if software such as Docker, cuda, or rocm is pre-installed on the node",
    )
    hardware: Optional[NodeHardware] = None
    software: Optional[NodeSoftware] = None
    system: Optional[NodeSystem] = None
    __properties: ClassVar[List[str]] = [
        "id",
        "node_type",
        "namespace",
        "hostname",
        "description",
        "location",
        "import_time",
        "node_status",
        "warning_message",
        "hardware",
        "software",
        "system",
    ]

    @field_validator("node_type")
    def node_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["CLOUD", "SELF_MANAGED"]):
            raise ValueError("must be one of enum values ('CLOUD', 'SELF_MANAGED')")
        return value

    @field_validator("node_status")
    def node_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(
            [
                "PENDING",
                "DISCOVERING",
                "AVAILABLE",
                "ADDED",
                "DEPLOYED",
                "FAILED",
                "WARNING",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('PENDING', 'DISCOVERING', 'AVAILABLE', 'ADDED', 'DEPLOYED', 'FAILED', 'WARNING')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    # JSON field name that stores the object type
    __discriminator_property_name: ClassVar[str] = "node_type"

    # discriminator mappings
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        "CLOUD": "CloudNode",
        "SELF_MANAGED": "SelfManagedNode",
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Union[CloudNode, SelfManagedNode]]:
        """Create an instance of BaseNode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of hardware
        if self.hardware:
            _dict["hardware"] = self.hardware.to_dict()
        # override the default output from pydantic by calling `to_dict()` of software
        if self.software:
            _dict["software"] = self.software.to_dict()
        # override the default output from pydantic by calling `to_dict()` of system
        if self.system:
            _dict["system"] = self.system.to_dict()
        return _dict

    @classmethod
    def from_dict(
        cls, obj: Dict[str, Any]
    ) -> Optional[Union[CloudNode, SelfManagedNode]]:
        """Create an instance of BaseNode from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type == "CloudNode":
            return import_module(
                "exalsius_api_client.models.cloud_node"
            ).CloudNode.from_dict(obj)
        if object_type == "SelfManagedNode":
            return import_module(
                "exalsius_api_client.models.self_managed_node"
            ).SelfManagedNode.from_dict(obj)

        raise ValueError(
            "BaseNode failed to lookup discriminator value from "
            + json.dumps(obj)
            + ". Discriminator property name: "
            + cls.__discriminator_property_name
            + ", mapping: "
            + json.dumps(cls.__discriminator_value_class_map)
        )
