# coding: utf-8

"""
exalsius API

The exalsius REST API enables programmatic access to GPU infrastructure management and orchestration capabilities. Access the API through the `exls` command-line tool or integrate it directly into your applications using standard HTTP requests. The API covers several areas: * **GPU Market Offers** Browse and compare GPU instance pricing across public cloud providers and hyperscalers. * **Operator Integration** Coordinates with the [exalsius-operator](https://github.com/exalsius/exalsius-operator) running in a management Kubernetes cluster to handle infrastructure provisioning and node lifecycle management. * **Node Management** Import cloud-provider instances or self-managed nodes (via SSH) into your node pool. Hardware characteristics of self-managed nodes are discovered automatically. * **Cluster Provisioning** Create and manage Kubernetes clusters on supported cloud providers or self-managed bare-metal infrastructure. * **Service Deployment** Deploy infrastructure services such as the NVIDIA GPU Operator, KubeRay, Flyte, or Kubeflow onto your clusters. * **Workspace Deployment** Provision application workloads including Jupyter Notebook servers, LLM inference services, and other compute workloads on your clusters.

The version of the OpenAPI document: 1.34.4
Contact: support@exalsius.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import (BaseModel, ConfigDict, Field, StrictFloat, StrictInt,
                      StrictStr, field_validator)
from typing_extensions import Self

from exalsius_api_client.models.gpu_type_info import GpuTypeInfo


class OfferMetadataResponse(BaseModel):
    """
    OfferMetadataResponse
    """  # noqa: E501

    gpu_types: List[GpuTypeInfo] = Field(
        description="Distinct GPU types currently available in offers."
    )
    gpu_vendors: List[StrictStr]
    cloud_providers: List[StrictStr]
    regions: List[StrictStr]
    availability_zones: List[StrictStr]
    locations: List[StrictStr]
    cpu_vendors: List[StrictStr]
    cpu_architectures: List[StrictStr]
    pricing_units: List[StrictStr]
    price_types: List[StrictStr]
    currencies: List[StrictStr]
    gpu_count_min: StrictInt = Field(
        description="Minimum GPU count observed across offers."
    )
    gpu_count_max: StrictInt = Field(
        description="Maximum GPU count observed across offers."
    )
    gpu_memory_mib_min: StrictInt = Field(
        description="Minimum per-GPU memory (MiB) observed across offers."
    )
    gpu_memory_mib_max: StrictInt = Field(
        description="Maximum per-GPU memory (MiB) observed across offers."
    )
    total_gpu_memory_mib_min: StrictInt = Field(
        description="Minimum total GPU memory (MiB) observed across offers."
    )
    total_gpu_memory_mib_max: StrictInt = Field(
        description="Maximum total GPU memory (MiB) observed across offers."
    )
    main_memory_mib_min: StrictInt = Field(
        description="Minimum system memory (MiB) observed across offers."
    )
    main_memory_mib_max: StrictInt = Field(
        description="Maximum system memory (MiB) observed across offers."
    )
    num_vcpus_min: StrictInt = Field(
        description="Minimum vCPU count observed across offers."
    )
    num_vcpus_max: StrictInt = Field(
        description="Maximum vCPU count observed across offers."
    )
    price_min: Union[StrictFloat, StrictInt] = Field(
        description="Minimum raw price observed across offers."
    )
    price_max: Union[StrictFloat, StrictInt] = Field(
        description="Maximum raw price observed across offers."
    )
    hourly_cost_min: Union[StrictFloat, StrictInt] = Field(
        description="Minimum normalized hourly cost observed across offers."
    )
    hourly_cost_max: Union[StrictFloat, StrictInt] = Field(
        description="Maximum normalized hourly cost observed across offers."
    )
    __properties: ClassVar[List[str]] = [
        "gpu_types",
        "gpu_vendors",
        "cloud_providers",
        "regions",
        "availability_zones",
        "locations",
        "cpu_vendors",
        "cpu_architectures",
        "pricing_units",
        "price_types",
        "currencies",
        "gpu_count_min",
        "gpu_count_max",
        "gpu_memory_mib_min",
        "gpu_memory_mib_max",
        "total_gpu_memory_mib_min",
        "total_gpu_memory_mib_max",
        "main_memory_mib_min",
        "main_memory_mib_max",
        "num_vcpus_min",
        "num_vcpus_max",
        "price_min",
        "price_max",
        "hourly_cost_min",
        "hourly_cost_max",
    ]

    @field_validator("gpu_vendors")
    def gpu_vendors_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(
                ["NVIDIA", "AMD", "INTEL", "HUAWEI", "GOOGLE", "AWS", "UNKNOWN"]
            ):
                raise ValueError(
                    "each list item must be one of ('NVIDIA', 'AMD', 'INTEL', 'HUAWEI', 'GOOGLE', 'AWS', 'UNKNOWN')"
                )
        return value

    @field_validator("cloud_providers")
    def cloud_providers_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(
                [
                    "AWS",
                    "AZURE",
                    "GCP",
                    "OCI",
                    "LAMBDA",
                    "PAPERSPACE",
                    "VAST",
                    "FLUIDSTACK",
                    "CUDO",
                    "NEBIUS",
                    "HYPERBOLIC",
                    "SCP",
                    "DO",
                    "OVHCLOUD",
                    "SCALEWAY",
                    "PRIMEINTELLECT",
                    "IBM",
                    "UNKNOWN",
                ]
            ):
                raise ValueError(
                    "each list item must be one of ('AWS', 'AZURE', 'GCP', 'OCI', 'LAMBDA', 'PAPERSPACE', 'VAST', 'FLUIDSTACK', 'CUDO', 'NEBIUS', 'HYPERBOLIC', 'SCP', 'DO', 'OVHCLOUD', 'SCALEWAY', 'PRIMEINTELLECT', 'IBM', 'UNKNOWN')"
                )
        return value

    @field_validator("cpu_vendors")
    def cpu_vendors_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(["INTEL", "AMD", "UNKNOWN"]):
                raise ValueError(
                    "each list item must be one of ('INTEL', 'AMD', 'UNKNOWN')"
                )
        return value

    @field_validator("cpu_architectures")
    def cpu_architectures_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(["X86_64", "AARCH64", "ARM64", "UNKNOWN"]):
                raise ValueError(
                    "each list item must be one of ('X86_64', 'AARCH64', 'ARM64', 'UNKNOWN')"
                )
        return value

    @field_validator("pricing_units")
    def pricing_units_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(["HOURLY", "MONTHLY", "YEARLY", "UNKNOWN"]):
                raise ValueError(
                    "each list item must be one of ('HOURLY', 'MONTHLY', 'YEARLY', 'UNKNOWN')"
                )
        return value

    @field_validator("price_types")
    def price_types_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(["ON_DEMAND", "SPOT"]):
                raise ValueError("each list item must be one of ('ON_DEMAND', 'SPOT')")
        return value

    @field_validator("currencies")
    def currencies_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(["USD", "EUR", "UNKNOWN"]):
                raise ValueError(
                    "each list item must be one of ('USD', 'EUR', 'UNKNOWN')"
                )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OfferMetadataResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in gpu_types (list)
        _items = []
        if self.gpu_types:
            for _item_gpu_types in self.gpu_types:
                if _item_gpu_types:
                    _items.append(_item_gpu_types.to_dict())
            _dict["gpu_types"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OfferMetadataResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "gpu_types": (
                    [GpuTypeInfo.from_dict(_item) for _item in obj["gpu_types"]]
                    if obj.get("gpu_types") is not None
                    else None
                ),
                "gpu_vendors": obj.get("gpu_vendors"),
                "cloud_providers": obj.get("cloud_providers"),
                "regions": obj.get("regions"),
                "availability_zones": obj.get("availability_zones"),
                "locations": obj.get("locations"),
                "cpu_vendors": obj.get("cpu_vendors"),
                "cpu_architectures": obj.get("cpu_architectures"),
                "pricing_units": obj.get("pricing_units"),
                "price_types": obj.get("price_types"),
                "currencies": obj.get("currencies"),
                "gpu_count_min": obj.get("gpu_count_min"),
                "gpu_count_max": obj.get("gpu_count_max"),
                "gpu_memory_mib_min": obj.get("gpu_memory_mib_min"),
                "gpu_memory_mib_max": obj.get("gpu_memory_mib_max"),
                "total_gpu_memory_mib_min": obj.get("total_gpu_memory_mib_min"),
                "total_gpu_memory_mib_max": obj.get("total_gpu_memory_mib_max"),
                "main_memory_mib_min": obj.get("main_memory_mib_min"),
                "main_memory_mib_max": obj.get("main_memory_mib_max"),
                "num_vcpus_min": obj.get("num_vcpus_min"),
                "num_vcpus_max": obj.get("num_vcpus_max"),
                "price_min": obj.get("price_min"),
                "price_max": obj.get("price_max"),
                "hourly_cost_min": obj.get("hourly_cost_min"),
                "hourly_cost_max": obj.get("hourly_cost_max"),
            }
        )
        return _obj
