# coding: utf-8

"""
exalsius API

The exalsius REST API provides programmatic access to the core functionality of the exalsius ecosystem It is consumed directly by the exls CLI tool and can also be integrated into custom applications or scripts. Key points: * **CLI & Programmatic Access**   All operations are available via the `exls` command-line application or through standard HTTP requests.  * **GPU Market Offers** Retrieve and compare GPU instance pricing across public cloud providers and hyperscalers to identify the most cost-effective options. * **Operator Integration**   Works in conjunction with the [exalsius-operator](https://github.com/exalsius/exalsius-operator) deployed in a management Kubernetes cluster, to manage infrastructure and node lifecycles.  * **Node Management**   Import self-managed (SSH) and cloud-provider instances into your node pool with dedicated endpoints.  * **Cluster Provisioning**   Create and manage Kubernetes clusters across supported cloud providers and self-managed (bare-metal) nodes.  * **Service Deployment**   Deploy additional services—such as the NVIDIA GPU Operator, KubeRay, Flyte, or Kubeflow—using the API’s service-deployment endpoints.

The version of the OpenAPI document: 1.1.0
Contact: support@exalsius.ai
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import (BaseModel, ConfigDict, Field, StrictFloat, StrictInt,
                      StrictStr)
from typing_extensions import Self


class Offer(BaseModel):
    """
    Offer
    """  # noqa: E501

    id: StrictStr = Field(description="The unique identifier for the offer")
    provider: StrictStr = Field(description="The cloud provider of the offer")
    location: StrictStr = Field(description="The location of the offer")
    region: StrictStr = Field(description="The region of the offer")
    availability_zone: StrictStr = Field(
        description="The availability zone of the offer"
    )
    instance_type: StrictStr = Field(description="The instance type of the offer")
    gpu_count: StrictInt = Field(description="The number of GPUs in the offer")
    gpu_vendor: StrictStr = Field(description="The vendor of the GPU")
    gpu_type: StrictStr = Field(description="The type of the GPU")
    gpu_memory: StrictInt = Field(description="The memory of the GPU in GB")
    price_per_hour: Union[StrictFloat, StrictInt] = Field(
        description="The price per hour for the offer"
    )
    scrape_time: datetime = Field(description="The time the offer was scraped")
    __properties: ClassVar[List[str]] = [
        "id",
        "provider",
        "location",
        "region",
        "availability_zone",
        "instance_type",
        "gpu_count",
        "gpu_vendor",
        "gpu_type",
        "gpu_memory",
        "price_per_hour",
        "scrape_time",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Offer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Offer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "provider": obj.get("provider"),
                "location": obj.get("location"),
                "region": obj.get("region"),
                "availability_zone": obj.get("availability_zone"),
                "instance_type": obj.get("instance_type"),
                "gpu_count": obj.get("gpu_count"),
                "gpu_vendor": obj.get("gpu_vendor"),
                "gpu_type": obj.get("gpu_type"),
                "gpu_memory": obj.get("gpu_memory"),
                "price_per_hour": obj.get("price_per_hour"),
                "scrape_time": obj.get("scrape_time"),
            }
        )
        return _obj
