get:
  operationId: getClusterServices
  tags: [clusters]
  summary: Get services of a cluster
  description: |
    **Get services of a cluster**

    Get all services deployed in a cluster.
    
    **Result**

    Returns an array of service IDs deployed in the cluster
    To gather more information about a service, call the `GET /services/{serviceId}` endpoint.

  parameters:
    - name: cluster_id
      in: path
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '200':
      $ref: '../../components/responses/cluster-services-response.yaml'
    '404':
      description: Cluster not found
      content:
        application/problem+json:
          schema:
            $ref: '../../components/schemas/error.yaml'
          example:
            type: "https://api.exalsius.ai/errors/not-found"
            title: "Not Found"
            status: 404
            detail: "The cluster with ID 123 was not found."
            instance: "/clusters/123"
    '500':
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '../../components/schemas/error.yaml'
          example:
            type: "https://api.exalsius.ai/errors/server-error"
            title: "Internal Server Error"
            status: 500
            detail: "An internal server error occurred while processing the request."
            instance: "/clusters/123/services"
  x-codeSamples:
    - lang: curl
      label: cURL
      source: |
        curl -X GET "https://api.exalsius.ai/clusters/123e4567-e89b-12d3-a456-426614174000/services"
    - lang: python
      label: Python
      source: |
        import requests
        response = requests.get("https://api.exalsius.ai/clusters/123e4567-e89b-12d3-a456-426614174000/services")
        print(response.json())

post:
  operationId: addClusterServices
  tags: [clusters]
  summary: Add service deployments to a cluster
  description: |
    **Add services to a cluster**

    Add services to a cluster.

    **Parameters**

    - `clusterId`: The ID of the cluster to add services to.

    **Request Body**

    - `serviceDeployments`: An array of service deployments to be deployed to the cluster.    
    
  parameters:
    - name: cluster_id
      in: path
      required: true
      schema:
        type: integer
        format: int64
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../components/requests/cluster-add-service-request.yaml'
  responses:
    '201':
      $ref: '../../components/responses/cluster-services-response.yaml'
    '400':
      description: Invalid service deployments
      content:
        application/problem+json:
          schema:
            $ref: '../../components/schemas/error.yaml'
          example:
            type: "https://api.exalsius.ai/errors/bad-request"
            title: "Bad Request"
            status: 400
            detail: "Invalid service deployments"
            instance: "/clusters/123/services"
    '404':
      description: Cluster not found
      content:
        application/problem+json:
          schema:
            $ref: '../../components/schemas/error.yaml'
          example:
            type: "https://api.exalsius.ai/errors/not-found"
            title: "Not Found"
            status: 404
            detail: "The cluster with ID 123 was not found."
            instance: "/clusters/123"
    '500':
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '../../components/schemas/error.yaml'
          example:
            type: "https://api.exalsius.ai/errors/server-error"
            title: "Internal Server Error"
            status: 500
            detail: "An internal server error occurred while processing the request."
            instance: "/clusters/123/services"
  x-codeSamples:
    - lang: curl
      label: cURL
      source: |
        curl -X POST "https://api.exalsius.ai/clusters/123e4567-e89b-12d3-a456-426614174000/services"
        -H "Content-Type: application/json"
        -d '{"serviceDeployments": [{"serviceId": "ffd4c2f4-ec48-41f1-be56-52ba90f661b6", "values": {"key": "value"}}, {"serviceId": "ffd4c2f4-ec48-41f1-be56-52ba90f661b7", "values": {"key": "value"}}]'
    - lang: python
      label: Python
      source: |
        import requests
        response = requests.post("https://api.exalsius.ai/clusters/123e4567-e89b-12d3-a456-426614174000/services", json={"serviceDeployments": [{"serviceId": "ffd4c2f4-ec48-41f1-be56-52ba90f661b6", "values": {"key": "value"}}, {"serviceId": "ffd4c2f4-ec48-41f1-be56-52ba90f661b7", "values": {"key": "value"}}]}
        print(response.json())
