name: Generate API Client Code

on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Generate client code
        run: make generate

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add client-sdk/
          git commit -m "chore: update generated client sdk" || exit 0
          git push
