name: Build & Publish OpenAPI Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install package.json dependencies
        run: make install

      - name: Bundle spec
        run: make build

      - name: Determine previous tag
        id: prev
        run: |
          PREV=$(git tag --sort=-version:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+' | sed -n '2p')
          echo "PREV_TAG=$PREV" >> $GITHUB_ENV

      - name: Bundle previous spec
        run: |
          git fetch --tags
          git checkout $PREV_TAG
          redocly bundle openapi/openapi.yaml -o prev_bundle.yaml
          git checkout -

      - name: Generate changelog via diff
        run: |
          openapi-diff-cli prev_bundle.yaml dist/bundle.yaml > API_CHANGELOG.md

      - name: Create GitHub release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/bundle.yaml
            API_CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}