on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish-release-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Build bundled openapi spec
        run: |
          make build

      - name: Rename bundle.yaml to versioned name
        run: |
          mv dist/bundle.yaml dist/exalsius-openapi-${{ github.event.release.tag_name }}.yaml

      - name: Upload release assets
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: |
            dist/exalsius-openapi-${{ github.event.release.tag_name }}.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
