name: Lint OpenAPI Spec

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Redocly CLI
        run: make install

      - name: Lint OpenAPI
        run: make lint
