name: Lint OpenAPI Spec

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Lint OpenAPI Spec with Spectral
        run: make lint
