name: Test Client SDK

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Generate client-sdk
        run: make generate

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: ./client-sdk
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Run tests
        working-directory: ./client-sdk
        run: pytest --cov ./ --junitxml=test-report.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: client-sdk/coverage.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: client-sdk/test-report.xml

      - name: Publish test results
        uses: dorny/test-reporter@v2
        with:
          name: Unit Tests
          path: client-sdk/test-report.xml
          reporter: java-junit